### PR TITLE
add arm support for tinycore

### PR DESCRIPTION
**Pull request by Kyle-Kyle**

### CODE REVIEW

**Comment by rhelmot** [comment]
oh lord help us

**Comment by Kyle-Kyle** [comment]
lol. I just realized that `tinycore` is very similar to `cle.elfcore`. maybe we should get rid of `tinycore` and import from `cle.elfcore`?

**Comment by rhelmot** [comment]
presumably tinycore was copied from elfcore's code at some point for some specific reason, possibly performance? I cannot tell you what lies down that road

**Comment by Kyle-Kyle** [comment]
This patch is important for everything to work. Can we merge it for now and then resolve the tinycore, ELFCore stuff later?

**Comment by rhelmot** [comment]
:pausechamp:

**Pull request merged**
