### PR TITLE
Rex needs this

### PR DESCRIPTION
**Pull request by tyb0807**
@rhelmot @salls please review this. Thanks!

### CODE REVIEW

**Comment by zardus** [comment]
Wouldn't this get wiped in the tracer merge anyways?

**Comment by tyb0807** [comment]
Yes, but if you want to fix rex first (that's what I'm doing), you'll need to fix the old tracer with this.

**Comment by zardus** [comment]
So to confirm: you want to merge this, and rebase your tracer-merge PR on top of it?

**Comment by tyb0807** [comment]
Yup, otherwise you cannot verify rex fixes can you?

**Comment by zardus** [comment]
From my personal perspective, fixing rex with the current state is useful only to help make sure it works after the tracer merge. If you tell me it works, then we end up merging the tracer into angr and it still works, then that's good enough for me :-)

That being said, I'm down to merge this. @salls, can you sign off? I don't know this part enough to judge.

**Comment by tyb0807** [comment]
I see, so please feel free to close this. The most important thing now is fixing rex anyways, I need your help on that :(

**Comment by salls** [comment]
Looks good to me

**Pull request merged**
