### PR TITLE
Adding argv option and default.

### PR DESCRIPTION
**Pull request by bannsec**
Adding option to specify argv and have it default to using the supplied binary name as the file name.

### CODE REVIEW

**Comment by bannsec** [comment]
not sure why that colorguard check is failing..

**Comment by zardus** [comment]
Travis should really have an option to auto-retry failed builds (or we should look into the flaky plugin for nosetests). Some of these tests fail intermittently. Let's see if this was such a case.

**Comment by bannsec** [comment]
Hah. Yeah, passed this time.

**Comment by ltfish** [comment]
@zardus IMO we should fix our tests...

**Comment by zardus** [comment]
Rather than use flaky? I'm all for it, but launching binaries and such (which we do in some of our tests) always has inherent race conditions, so it'll be hard to eliminate all race conditions. IMO, flaky is a good bandaid as well.

**Comment by salls** [comment]
Thanks!

**Pull request merged**
